# Generated by Django 3.2.5 on 2021-12-06 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20211206_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_notifications',
            name='Notification_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 6, 17, 23, 8, 446845)),
        ),
        migrations.AlterField(
            model_name='vendor_notifications',
            name='Notification_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 6, 17, 23, 8, 446845)),
        ),
    ]
