# Generated by Django 3.2.5 on 2021-12-06 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='img6',
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 6, 17, 23, 8, 456483)),
        ),
        migrations.AlterField(
            model_name='blogs_comments',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 6, 17, 23, 8, 457480)),
        ),
    ]
