# Generated by Django 3.2.5 on 2021-12-06 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20211206_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs_comments',
            name='comment_subject',
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 6, 19, 23, 39, 451466)),
        ),
        migrations.AlterField(
            model_name='blogs_comments',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 6, 19, 23, 39, 451466)),
        ),
    ]
